import streamlit as st
import re
import io
import pdfplumber
from docx import Document

SKILLS_DB = {
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "Perl",
    "HTML",
    "CSS",
    "SQL",
    "NoSQL",
    "Bash",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Django",
    "Flask",
    "Spring Boot",
    "Express.js",
    "Next.js",
    "Nuxt.js",
    "FastAPI",
    "ASP.NET",
    "Ruby on Rails",
    "Laravel",
    "Symfony",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "OpenCV",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Terraform",
    "Ansible",
    "Jenkins",
    "Git",
    "GitHub Actions",
    "CI/CD",
    "Linux",
    "Nginx",
    "Apache",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Redis",
    "Elasticsearch",
    "Cassandra",
    "Oracle",
    "GraphQL",
    "REST API",
    "gRPC",
    "WebSocket",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "Data Science",
    "Agile",
    "Scrum",
    "JIRA",
    "Confluence",
    "Communication",
    "Leadership",
    "Teamwork",
    "Problem Solving",
    "Critical Thinking",
}


def extract_text_from_pdf(file_bytes):
    text = ""
    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    return text


def extract_text_from_docx(file_bytes):
    doc = Document(io.BytesIO(file_bytes))
    return "\n".join([p.text for p in doc.paragraphs])


def extract_text(file, ext):
    if ext == "pdf":
        return extract_text_from_pdf(file.read())
    elif ext == "docx":
        return extract_text_from_docx(file.read())
    return ""


def extract_skills(text):
    found = set()
    text_lower = text.lower()
    for skill in SKILLS_DB:
        pattern = r"\b" + re.escape(skill.lower()) + r"\b"
        if re.search(pattern, text_lower):
            found.add(skill)
    return sorted(found)


def compute_score(resume_skills, jd_skills):
    if not jd_skills:
        return 0.0, [], []
    matched = [s for s in jd_skills if s in resume_skills]
    missing = [s for s in jd_skills if s not in resume_skills]
    score = round(len(matched) / len(jd_skills) * 100, 1)
    return score, matched, missing


def generate_report(
    name, resume_text, resume_skills, jd_text, jd_skills, score, matched, missing
):
    lines = []
    lines.append("=" * 60)
    lines.append("RESUME ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append(f"Candidate: {name}")
    lines.append(
        f"Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}"
    )
    lines.append("")
    lines.append("--- Resume Skills Found ---")
    lines.append(", ".join(resume_skills) if resume_skills else "None")
    lines.append("")
    lines.append("--- Job Description Skills ---")
    lines.append(", ".join(jd_skills) if jd_skills else "None")
    lines.append("")
    lines.append(f"--- Compatibility Score: {score}% ---")
    lines.append("")
    lines.append("--- Matched Skills ---")
    lines.append(", ".join(matched) if matched else "None")
    lines.append("")
    lines.append("--- Missing Skills (Suggestions) ---")
    if missing:
        for s in missing:
            lines.append(f"  + {s}")
    else:
        lines.append("  None - Perfect match!")
    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by AI Resume Analyzer")
    return "\n".join(lines)


st.set_page_config(page_title="AI Resume Analyzer", page_icon="📄", layout="centered")
st.title("📄 AI-Powered Resume Analyzer")

tab1, tab2 = st.tabs(["Analyze Resume", "Demo"])

with tab1:
    col1, col2 = st.columns(2)
    with col1:
        uploaded = st.file_uploader("Upload Resume (PDF/DOCX)", type=["pdf", "docx"])
        name = st.text_input("Candidate Name", "John Doe")
    with col2:
        jd_text = st.text_area(
            "Paste Job Description",
            height=200,
            placeholder="Paste the job description here...",
        )

    if uploaded and jd_text.strip():
        ext = uploaded.name.split(".")[-1].lower()
        with st.spinner("Analyzing resume..."):
            resume_text = extract_text(uploaded, ext)
            resume_skills = extract_skills(resume_text)
            jd_skills = extract_skills(jd_text)
            score, matched, missing = compute_score(resume_skills, jd_skills)

        st.subheader("Results")

        col_score, col_match, col_miss = st.columns(3)
        col_score.metric("Compatibility Score", f"{score}%")
        col_match.metric("Matched Skills", len(matched))
        col_miss.metric("Missing Skills", len(missing))

        st.progress(score / 100)

        s1, s2 = st.columns(2)
        with s1:
            st.write("**Resume Skills**")
            st.write(", ".join(resume_skills) if resume_skills else "None found")
            if not resume_skills:
                st.info("No skills detected. Try a clearer resume format.")

        with s2:
            st.write("**Job Description Skills**")
            st.write(", ".join(jd_skills) if jd_skills else "None found")

        st.write("**✅ Matched Skills**")
        if matched:
            st.success(", ".join(matched))
        else:
            st.warning("No direct skill matches found.")

        st.write("**💡 Suggested Skills to Add**")
        if missing:
            for s in missing:
                st.markdown(f"- **{s}**")
        else:
            st.success("Great match! No missing skills.")

        report = generate_report(
            name,
            resume_text,
            resume_skills,
            jd_text,
            jd_skills,
            score,
            matched,
            missing,
        )
        st.download_button(
            "📥 Download Report",
            report,
            file_name=f"{name}_report.txt",
            mime="text/plain",
        )
    elif uploaded and not jd_text.strip():
        st.info("Please paste a Job Description to compare.")
    elif not uploaded and jd_text.strip():
        st.info("Please upload a resume file.")

with tab2:
    st.subheader("Demo Mode - Try with Sample Data")

    if st.button("Run Demo Analysis"):
        demo_resume = """
        Experienced software engineer with strong Python and JavaScript skills.
        Proficient in React, Node.js, and working with MongoDB and PostgreSQL databases.
        Familiar with Docker, AWS, and CI/CD pipelines.
        Strong problem-solving and teamwork abilities.
        """
        demo_jd = """
        We are looking for a Full Stack Developer with expertise in Python, JavaScript, React, Node.js,
        MongoDB, and AWS. Knowledge of Docker and Kubernetes is a plus. Strong communication and
        teamwork skills required.
        """

        with st.spinner("Running demo..."):
            resume_skills = extract_skills(demo_resume)
            jd_skills = extract_skills(demo_jd)
            score, matched, missing = compute_score(resume_skills, jd_skills)

        st.write("**Sample Resume**")
        st.code(demo_resume.strip())
        st.write("**Sample Job Description**")
        st.code(demo_jd.strip())

        col1, col2, col3 = st.columns(3)
        col1.metric("Compatibility Score", f"{score}%")
        col2.metric("Matched Skills", len(matched))
        col3.metric("Missing Skills", len(missing))

        st.progress(score / 100)

        st.write("**Skills Found in Resume:** " + ", ".join(resume_skills))
        st.write("**Skills in Job Description:** " + ", ".join(jd_skills))
        st.write("**✅ Matched:** " + ", ".join(matched))
        st.write("**💡 Missing (Consider adding):**")
        for s in missing:
            st.markdown(f"- **{s}**")

        report = generate_report(
            "Demo Candidate",
            demo_resume,
            resume_skills,
            demo_jd,
            jd_skills,
            score,
            matched,
            missing,
        )
        st.download_button(
            "📥 Download Demo Report", report, file_name="demo_report.txt"
        )

    st.markdown("---")
    st.markdown(
        "**Tip:** Upload a real PDF/DOCX resume in the *Analyze Resume* tab for actual analysis."
    )
